<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="0" started-at="2019-10-17T13:38:31Z" finished-at="2019-10-17T13:38:31Z">
    <groups>
    </groups>
  </suite> <!-- Suite -->
  <suite name="Suite (0)" duration-ms="1591" started-at="2019-10-17T13:38:29Z" finished-at="2019-10-17T13:38:31Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="1591" started-at="2019-10-17T13:38:29Z" finished-at="2019-10-17T13:38:31Z">
      <class name="com.atmecs.atmecs_automation.testscripts.TestVerifyBlogs">
        <test-method status="FAIL" signature="verifyBlogsAndComments()[pri:0, instance:com.atmecs.atmecs_automation.testscripts.TestVerifyBlogs@77b52d12]" name="verifyBlogsAndComments" duration-ms="1556" started-at="2019-10-17T13:38:29Z" finished-at="2019-10-17T13:38:31Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.atmecs.atmecs_automation.utils.DatabaseReader.insertQuery(DatabaseReader.java:21)
at com.atmecs.atmecs_automation.testscripts.TestVerifyBlogs.verifyBlogsAndComments(TestVerifyBlogs.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyBlogsAndComments -->
      </class> <!-- com.atmecs.atmecs_automation.testscripts.TestVerifyBlogs -->
    </test> <!-- Test -->
  </suite> <!-- Suite (0) -->
</testng-results>
